<?php
$cidModel = $block->getCidModel();
$cidFields = $cidModel->getCidFields();
?>
<?php if ($cidFields): ?>
    <?php if ($cidFields->getShippingCidNumber() || $cidFields->getBillingCidNumber()): ?>
        <section class="admin__page-section">
            <div class="admin__page-section-title">
                <span class="title"><?php /* @escapeNotVerified */ echo __('Identification Document') ?></span>
            </div>
            <div class="admin__page-section-content">
                <div class="order-information">
                    <?php if ($cidFields->getShippingCidNumber()): ?>
                        <div class="box">
                            <strong class="box-title"><span><?php /* @escapeNotVerified */ echo __('Shipping') ?></span></strong>
                            <div class="box-content">
                                <?php echo $this->escapeHtml($cidFields->getShippingCidType()); ?>: <?php echo $this->escapeHtml($cidFields->getShippingCidNumber()); ?>
                            </div>
                        </div>
                    <?php endif; ?>
                    <?php if ($cidFields->getBillingCidNumber()): ?>
                        <div class="box">
                            <strong class="box-title"><span><?php /* @escapeNotVerified */ echo __('Billing') ?></span></strong>
                            <div class="box-content">
                                <?php echo $this->escapeHtml($cidFields->getBillingCidType()); ?>: <?php echo $this->escapeHtml($cidFields->getBillingCidNumber()); ?>
                            </div>
                        </div>
                    <?php endif; ?>
                </div>
            </div>
        </section>
    <?php endif; ?>
<?php endif; ?>
